### ISSUE TITLE
upgrade to latest react native sdk 0.64

### ISSUE THREAD

**Issue by DerekLiang** [danielstern/styling-react-native#2]
using reactive native cli to upgrade to sdk 0.64. and run `expo start`

```
% expo start
Starting project at /Users/xxx/react-native/styling-react-native
Developer tools running on http://localhost:19002
Opening developer tools in the browser...
Starting Metro Bundler
error listen EADDRINUSE: address already in use :::19000.

Error: listen EADDRINUSE: address already in use :::19000
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)

...
```

```
% expo --version
4.8.1
% node --version
v14.15.2
```

package.json
```
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "expo": "~38.0.9",
    "expo-splash-screen": "^0.5.0",
    "expo-status-bar": "^1.0.0",
    "expo-updates": "~0.2.10",
    "nanoid": "^3.1.12",
    "react": "17.0.1",
    "react-dom": "~16.11.0",
    "react-native": "0.64.2",
    "react-native-gesture-handler": "~1.6.1",
    "react-native-reanimated": "~1.9.0",
    "react-native-screens": "~2.9.0",
    "react-native-unimodules": "~0.10.1",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.11.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
```

**Comment by danielstern** [comment]
It looks like you may already have an instance of the app open. Have you tried restarting your workstation?
________________________________
From: Derek Liang ***@***.***>
Sent: July 26, 2021 2:18 AM
To: danielstern/styling-react-native ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [danielstern/styling-react-native] upgrade to latest react native sdk 0.64 (#2)


using reactive native cli to upgrade to sdk 0.64. and run expo start

% expo start
Starting project at /Users/xxx/react-native/styling-react-native
Developer tools running on http://localhost:19002
Opening developer tools in the browser...
Starting Metro Bundler
error listen EADDRINUSE: address already in use :::19000.

Error: listen EADDRINUSE: address already in use :::19000
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)

...

**Comment by DerekLiang** [comment]
I have to login as with a new profile to fix the issue.
